apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wp4dl0u6s-dotnet-basic
  janus-idp.io/tekton: wp4dl0u6s-dotnet-basic
  backstage.io/kubernetes-id: wp4dl0u6s-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wp4dl0u6s-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
